name: PhotoSwipeCleaner
options:
  bundleIdPrefix: com.yw
  developmentLanguage: en
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "-"
    DEVELOPMENT_TEAM: ""

targets:
  PhotoSwipeCleaner:
    type: application
    platform: iOS
    sources:
      - PhotoSwipeCleaner
    settings:
      base:
        INFOPLIST_FILE: PhotoSwipeCleaner/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yw.PhotoSwipeCleaner
        SWIFT_VERSION: "5.0"
        ENABLE_PREVIEWS: YES
        PRODUCT_NAME: PhotoSwipeCleaner
    dependencies: []

schemes:
  PhotoSwipeCleaner:
    build:
      targets:
        PhotoSwipeCleaner: all
    run:
      config: Debug
    archive:
      config: Release