name: PhotoSwipeCleaner
options:
  bundleIdPrefix: com.yw
  developmentLanguage: en
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "-"
    DEVELOPMENT_TEAM: ""

targets:
  PhotoSwipeCleaner:
    type: application
    platform: iOS
    sources:
      - PhotoSwipeCleaner
    settings:
      base:
        INFOPLIST_FILE: PhotoSwipeCleaner/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.yw.PhotoSwipeCleaner
        SWIFT_VERSION: "5.0"
        ENABLE_PREVIEWS: YES
        PRODUCT_NAME: PhotoSwipeCleaner
    dependencies: []

  PhotoSwipeCleanerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PhotoSwipeCleanerTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.yw.PhotoSwipeCleanerTests
        SWIFT_VERSION: "5.0"
    dependencies:
      - target: PhotoSwipeCleaner

  PhotoSwipeCleanerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - PhotoSwipeCleanerUITests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.yw.PhotoSwipeCleanerUITests
        SWIFT_VERSION: "5.0"
        TEST_TARGET_NAME: PhotoSwipeCleaner
    dependencies:
      - target: PhotoSwipeCleaner

schemes:
  PhotoSwipeCleaner:
    build:
      targets:
        PhotoSwipeCleaner: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: PhotoSwipeCleanerTests
        - name: PhotoSwipeCleanerUITests
    archive:
      config: Release
